version: '3'

services :
  client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    volumes:
      - ./client-app:/var/www/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true